language: node_js
node_js:
  - "10.10.0"
os:
  - linux
if: tag IS present
before_script:
  - npm install -g gulp-cli codecov
script: 
  - npm run release

deploy:
  provider: npm
  email: "pramod.aug.17@gmail.com"
  api_key: ${NPM_AUTH_TOKEN}
  on:
    tags: true