language: node_js
node_js:
  - "10.10"
os:
  - linux
  - osx
  - windows
before_script:
  - npm install -g gulp-cli
script: 
  - npm run release

deploy:
  provider: npm
  email: "YOUR_EMAIL_ADDRESS"
  api_key: "YOUR_AUTH_TOKEN"
  on:
    tags: true